// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDR8fGYBB2T8ORjJU1-17sF_VUjcsdF_Vo',
    appId: '1:23392353423:web:9011de8ba9cfb3dbb144fa',
    messagingSenderId: '23392353423',
    projectId: 'fluttergram-77cc0',
    authDomain: 'fluttergram-77cc0.firebaseapp.com',
    storageBucket: 'fluttergram-77cc0.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2wwLFKrhAWkBqx9ubIUHifNOCIGjMYmc',
    appId: '1:23392353423:android:c4f41af881513fceb144fa',
    messagingSenderId: '23392353423',
    projectId: 'fluttergram-77cc0',
    storageBucket: 'fluttergram-77cc0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhrVneih6rnRbvrNVAjMgqXkWQW6PDjoI',
    appId: '1:23392353423:ios:a8e700ea07d6d3c5b144fa',
    messagingSenderId: '23392353423',
    projectId: 'fluttergram-77cc0',
    storageBucket: 'fluttergram-77cc0.appspot.com',
    iosClientId: '23392353423-dck4pi1q8smig6m1bedn2posrm9iid96.apps.googleusercontent.com',
    iosBundleId: 'com.minki.instagram',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDhrVneih6rnRbvrNVAjMgqXkWQW6PDjoI',
    appId: '1:23392353423:ios:a8e700ea07d6d3c5b144fa',
    messagingSenderId: '23392353423',
    projectId: 'fluttergram-77cc0',
    storageBucket: 'fluttergram-77cc0.appspot.com',
    iosClientId: '23392353423-dck4pi1q8smig6m1bedn2posrm9iid96.apps.googleusercontent.com',
    iosBundleId: 'com.minki.instagram',
  );
}
